### ISSUE TITLE
[Improvement] Added additional sources + GUI

### ISSUE THREAD

**Issue by nixonjoshua98** [YouWatanabeStan/Kamiyomi#1]
Hi, I came across this as I maintain the Manganelo repo. I have another package for MangaKatana here (https://github.com/nixonjoshua98/mangakatana). I also have my own manga-tracker I use which uses Manganelo and MangaKatana here (https://github.com/nixonjoshua98/manga-tracker) if you wanted a reference for someone elses attempt.

I'd be interested to see a Desktop (Linux & Windows) version of tachiyomi.

Note, you should also use manganelo.rewrite since it will replace the classes which you use right now (https://github.com/nixonjoshua98/manganelo#rewrite-version-will-soon-become-standard)

**Comment by gskapoor** [comment]
Thanks for the tip and for making these repos.

I am going to separate them all into separate issues and work on them once I finally add basic source file addition/deletion.
